### Importing the Libraries

In [1]:
import pandas as pd
import pyodbc

print(pd.__version__)

3.0.5

### Loading the database

In [2]:
connect = pyodbc.connect(
    "Driver={ODBC Driver 17 for SQL Server};"
    r"Server=.\SQLEXPRESS;"
    "Database=MLOps_qafza;"
    "Trusted_Connection=yes;"
)

### Making some query

In [63]:
query = '''
    SELECT TOP 10 
	od.order_id,
	od.order_status,
	od.order_delivered_customer_date,
	od.order_estimated_delivery_date,
	oid.price,
	oid.shipping_limit_date,
	opd.payment_type,
	opd.payment_value
FROM dbo.olist_orders_dataset AS od
JOIN dbo.olist_order_items_dataset AS oid
ON od.order_id = oid.order_id
JOIN dbo.olist_order_payments_dataset AS opd
ON od.order_id = opd.order_id
'''


mask = pd.read_sql(query, connect)

mask

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11704\915346644.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mask = pd.read_sql(query, connect)

,order_id,order_status,order_delivered_customer_date,order_estimated_delivery_date,price,shipping_limit_date,payment_type,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,2017-10-10 21:25:13,2017-10-18,29.990000,2017-10-06 11:07:15,credit_card,18.120001
1,e481f51cbdc54678b7cc49136f2d6af7,delivered,2017-10-10 21:25:13,2017-10-18,29.990000,2017-10-06 11:07:15,voucher,2.000000
2,e481f51cbdc54678b7cc49136f2d6af7,delivered,2017-10-10 21:25:13,2017-10-18,29.990000,2017-10-06 11:07:15,voucher,18.590000
3,53cdb2fc8bc7dce0b6741e2150273451,delivered,2018-08-07 15:27:45,2018-08-13,118.699997,2018-07-30 03:24:27,boleto,141.460007
4,47770eb9100c2d0c44946d9cf07ec65d,delivered,2018-08-17 18:06:29,2018-09-04,159.899994,2018-08-13 08:55:23,credit_card,179.119995
5,949d5b44dbf5de918fe9c16f97b45f8a,delivered,2017-12-02 00:28:42,2017-12-15,45.000000,2017-11-23 19:45:59,credit_card,72.199997
6,ad21c59c0840e6cb83a9ceb5573f8159,delivered,2018-02-16 18:17:02,2018-02-26,19.900000,2018-02-19 20:31:37,credit_card,28.620001
7,a4591c265e18cb1dcee52889e2d8acc3,delivered,2017-07-26 10:57:55,2017-08-01,147.899994,2017-07-13 22:10:13,credit_card,175.259995
8,136cce7faa42fdb2cefd53fdc79a6098,invoiced,NaT,2017-05-09,49.900002,2017-04-19 13:25:17,credit_card,65.949997
9,6514b8ad8028c9f2cc2374ded245783f,delivered,2017-05-26 12:55:51,2017-06-07,59.990002,2017-05-22 13:22:11,credit_card,75.160004

### Work with tables

In [64]:
customers = pd.read_sql('SELECT * FROM dbo.olist_customers_dataset', connect)

sellers = pd.read_sql('SELECT * FROM dbo.olist_sellers_dataset', connect)

products = pd.read_sql('SELECT * FROM dbo.olist_products_dataset', connect)

product_category_name_translation = pd.read_sql('SELECT * FROM dbo.product_category_name_translation', connect)

geolocation = pd.read_sql('SELECT * FROM dbo.olist_geolocation_dataset', connect)

orders = pd.read_sql('SELECT * FROM dbo.olist_orders_dataset', connect)

order_items = pd.read_sql('SELECT * FROM dbo.olist_order_items_dataset', connect)

order_payments = pd.read_sql('SELECT * FROM dbo.olist_order_payments_dataset', connect)

order_reviews = pd.read_sql('SELECT * FROM dbo.olist_order_reviews_dataset', connect)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11704\2317773807.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers = pd.read_sql('SELECT * FROM dbo.olist_customers_dataset', connect)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11704\2317773807.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sellers = pd.read_sql('SELECT * FROM dbo.olist_sellers_dataset', connect)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11704\2317773807.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products = pd.read_sql('SELECT * FROM dbo.olist_products_dataset', connect)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11704\2317773807.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  product_category_name_translation = pd.read_sql('SELECT * FROM dbo.product_category_name_translation', connect)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11704\2317773807.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  geolocation = pd.read_sql('SELECT * FROM dbo.olist_geolocation_dataset', connect)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11704\2317773807.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders = pd.read_sql('SELECT * FROM dbo.olist_orders_dataset', connect)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11704\2317773807.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  order_items = pd.read_sql('SELECT * FROM dbo.olist_order_items_dataset', connect)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11704\2317773807.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  order_payments = pd.read_sql('SELECT * FROM dbo.olist_order_payments_dataset', connect)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11704\2317773807.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  order_reviews = pd.read_sql('SELECT * FROM dbo.olist_order_reviews_dataset', connect)

#### Shape of the tables

In [65]:
tables = {
    'Orders': orders,
    'Order Items': order_items,
    'Order Payments': order_payments,
    'Order Reviews': order_reviews,
    'Customers': customers,
    'Sellers': sellers,
    'Products': products,
    'Geolocation': geolocation,
    'Product Category Name Translation': product_category_name_translation
}

for name, df in tables.items():
    print(f'{name} shape -> {df.shape}')

Orders shape -> (99441, 8)
Order Items shape -> (112650, 7)
Order Payments shape -> (103886, 5)
Order Reviews shape -> (99224, 7)
Customers shape -> (99441, 5)
Sellers shape -> (3095, 4)
Products shape -> (32951, 9)
Geolocation shape -> (1000163, 5)
Product Category Name Translation shape -> (72, 2)

#### First two rows from tables

In [66]:
customers.head(2)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP

In [67]:
sellers.head(2)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP

In [68]:
products.head(2)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0

In [69]:
product_category_name_translation.head(2)

                 column1                        column2
0  product_category_name  product_category_name_english
1           beleza_saude                  health_beauty

In [70]:
geolocation.head(2)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545622,-46.639294,sao paulo,SP
1,1046,-23.546082,-46.644821,sao paulo,SP

In [71]:
orders.head(2)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13

In [72]:
order_items.head(2)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.900002,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.899994,19.93

In [73]:
order_payments.head(2)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.330002
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.389999

In [74]:
order_reviews.head(2)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10,2018-03-11 03:05:13

#### Check duplicates

In [75]:
for name, df in tables.items():
    if True in df.duplicated():
        print(f'Number of duplicates in {name} table is: {df.duplicated().sum()}')

In [76]:
customers.duplicated().sum()

np.int64(0)

#### Check uniqueness

In [77]:
print(f'customer id is unique in customers table? {customers['customer_id'].is_unique}')
print(f'seller id is unique in sellers table? {sellers['seller_id'].is_unique}')
print(f'product id is unique in products table? {products['product_id'].is_unique}')
print(f'order id is unique in orders table? {orders['order_id'].is_unique}')
print(f'order id is unique in order items table? {order_items['order_id'].is_unique}')
print(f'order id is unique in order payments table? {order_payments['order_id'].is_unique}')
print(f'order id is unique in order reviews table? {order_reviews['order_id'].is_unique}')

customer id is unique in customers table? True
seller id is unique in sellers table? True
product id is unique in products table? True
order id is unique in orders table? True
order id is unique in order items table? False
order id is unique in order payments table? False
order id is unique in order reviews table? False

In [78]:
order_items[['order_id', 'order_item_id']].duplicated().sum()

np.int64(0)

In [79]:
order_reviews[['order_id', 'review_id']].duplicated().sum()

np.int64(0)

#### Aggregation

In [80]:
order_items_agg = pd.read_sql('''SELECT 
	order_id,
	COUNT(order_item_id) AS item_count,
	SUM(price) AS total_price,
	SUM(freight_value) AS total_freight_value
FROM dbo.olist_order_items_dataset
GROUP BY order_id
''', connect)

order_items_agg

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11704\1644565933.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  order_items_agg = pd.read_sql('''SELECT

,order_id,item_count,total_price,total_freight_value
0,8e8f8ef29c78c7b9c98cac70dd331ce2,6,1020.000000,182.640003
1,061f31c732cb84a989d5b62660212ecc,1,69.989998,17.770000
2,fb5114c39f632a52598cf770c6076620,1,35.000000,16.049999
3,23fb5e6768dd0cf8df7aaa74d80f8ec6,1,55.000000,20.879999
4,7581c7decedb7d7f4310ef8313f935a7,1,34.900002,14.520000
...,...,...,...,...
98661,50cb3b5a9be182d708715a0ea7d488b0,1,24.900000,17.059999
98662,73627dfa9a67ee111fb528be6f9d4b02,1,34.990002,37.040001
98663,07220c39eb26068368e675009154d635,1,136.000000,18.830000
98664,5e9d20f05b27d15f099382c8d812e136,1,41.900002,10.960000
98665,614c0b4b5169af9eb895bc8aefe5a418,1,20.900000,12.810000

In [81]:
order_payments_agg = pd.read_sql('''SELECT
    order_id,
    COUNT(*) AS payment_count,
	SUM(payment_value) AS total_payment
FROM dbo.olist_order_payments_dataset
GROUP BY order_id;
''', connect)

order_payments_agg

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11704\816732954.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  order_payments_agg = pd.read_sql('''SELECT

                               order_id  payment_count  total_payment
0      d5a777d0e1c561e945c9eedce2cad80f              1      58.740002
1      ceaa40707ccad8de8d4dab476a970483              1      85.239998
2      aeef04fa986be504dfc33b096ac921df              1      94.309998
3      b12dbb55013ad2916d26c65c8abbcd17              1     226.580002
4      6cff0bbcafb7486dd85cda3c8171cf9a              1     253.899994
...                                 ...            ...            ...
99435  cab86f1b8802835f13e9fee67ae7ee13              1     206.139999
99436  78ef246c8a753452a6464f1f66603fac              1      88.559998
99437  ee5eb378ff9c7070eec20d9ac9a06688              1      40.000000
99438  06cc5452c0a830d345b93a5385ee310e              1      15.380000
99439  d99a07d049ac5c39f6f62edba8d57721              1     111.620003

[99440 rows x 3 columns]

### Build ML table

In [3]:
ml_table = pd.read_sql('''SELECT 
	o.order_id,
	o.customer_id,
	o.order_status,
	o.order_purchase_timestamp,
	o.order_approved_at,
	o.order_delivered_carrier_date,
	o.order_delivered_customer_date,
	o.order_estimated_delivery_date,

	c.customer_unique_id,
	c.customer_city,
	c.customer_state,
	c.customer_zip_code_prefix,

	i.item_count,
	i.total_price,
	i.total_freight_value,

	pay.payment_count,
	pay.total_payment,

	pro.avg_product_name_length,
	pro.avg_product_description_length,
	pro.avg_product_height_cm,
	pro.avg_product_length_cm,
	pro.avg_product_photos_qty,
	pro.avg_product_width_cm,
	pro.avg_product_weight_g,
	pro.product_count,

	sel.seller_count
FROM dbo.olist_orders_dataset AS o
LEFT JOIN dbo.olist_customers_dataset AS c
ON o.customer_id = c.customer_id
LEFT JOIN (
SELECT 
	order_id,
	COUNT(order_item_id) AS item_count,
	SUM(price) AS total_price,
	SUM(freight_value) AS total_freight_value
FROM dbo.olist_order_items_dataset
GROUP BY order_id) AS i
ON o.order_id = i.order_id
LEFT JOIN (
SELECT
	order_id,
	COUNT(*) AS payment_count,
	SUM(payment_value) AS total_payment
FROM dbo.olist_order_payments_dataset
GROUP BY order_id) AS pay
ON o.order_id = pay.order_id
LEFT JOIN (
SELECT 
	oi.order_id,
	COUNT(DISTINCT oi.product_id) AS product_count,
	AVG(pro.product_height_cm) AS avg_product_height_cm,
	AVG(pro.product_description_lenght) AS avg_product_description_length,
	AVG(pro.product_length_cm) AS avg_product_length_cm,
	AVG(pro.product_name_lenght) AS avg_product_name_length,
	AVG(pro.product_photos_qty) AS avg_product_photos_qty,
	AVG(pro.product_weight_g) AS avg_product_weight_g,
	AVG(pro.product_width_cm) AS avg_product_width_cm
FROM dbo.olist_order_items_dataset AS oi
LEFT JOIN dbo.olist_products_dataset AS pro
ON oi.product_id = pro.product_id
GROUP BY oi.order_id
) AS pro
ON o.order_id = pro.order_id
LEFT JOIN (
SELECT
	oi.order_id,
	COUNT(DISTINCT oi.seller_id) AS seller_count
FROM dbo.olist_order_items_dataset AS oi
GROUP BY oi.order_id) AS sel
ON o.order_id = sel.order_id''', connect)

ml_table

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_4148\4227996093.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ml_table = pd.read_sql('''SELECT

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_city,...,total_payment,avg_product_name_length,avg_product_description_length,avg_product_height_cm,avg_product_length_cm,avg_product_photos_qty,avg_product_width_cm,avg_product_weight_g,product_count,seller_count
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,871766c5855e863f6eccc05f988b23cb,campos dos goytacazes,...,72.190002,58.0,598.0,9.0,28.0,4.0,14.0,650.0,1.0,1.0
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,eb28e67c4c0b83846050ddfb8a35d051,santa fe do sul,...,259.829987,56.0,239.0,30.0,50.0,2.0,40.0,30000.0,1.0,1.0
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,3818d81c6709e39d06b2738a8d3a2474,para de minas,...,216.869995,59.0,695.0,13.0,33.0,2.0,33.0,3050.0,1.0,1.0
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,af861d436cfc08b2c2ddefd0ba074622,atibaia,...,25.780001,42.0,480.0,10.0,16.0,1.0,15.0,200.0,1.0,1.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,64b576fb70d441e8f1b2d7d446e483c5,varzea paulista,...,218.039993,59.0,409.0,40.0,35.0,1.0,30.0,3750.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,fffc94f6ce00a00581880bf54a75a037,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,2018-04-25 04:11:01,2018-04-25 12:09:00,2018-05-10 22:56:40,2018-05-18,0c9aeda10a71f369396d0c04dce13a64,sao luis,...,343.399994,43.0,1002.0,15.0,89.0,3.0,40.0,10150.0,1.0,1.0
99437,fffcd46ef2263f404302a634eb57f7eb,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,2018-07-17 04:31:48,2018-07-17 08:05:00,2018-07-23 20:31:55,2018-08-01,0da9fe112eae0c74d3ba1fe16de0988b,curitiba,...,386.529999,31.0,232.0,26.0,45.0,1.0,38.0,8950.0,1.0,1.0
99438,fffce4705a9662cd70adb13d4a31832d,29309aa813182aaddc9b259e31b870e6,delivered,2017-10-23 17:07:56,2017-10-24 17:14:25,2017-10-26 15:13:14,2017-10-28 12:22:22,2017-11-10,cd79b407828f02fdbba457111c38e4c4,sao paulo,...,116.849998,43.0,869.0,24.0,21.0,1.0,19.0,967.0,1.0,1.0
99439,fffe18544ffabc95dfada21779c9644f,b5e6afd5a41800fdf401e0272ca74655,delivered,2017-08-14 23:02:59,2017-08-15 00:04:32,2017-08-15 19:02:53,2017-08-16 21:59:40,2017-08-25,eb803377c9315b564bdedad672039306,vinhedo,...,64.709999,56.0,1306.0,20.0,20.0,1.0,20.0,100.0,1.0,1.0
99440,fffe41c64501cc87c801fd61db3f6244,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,2018-06-09 17:10:13,2018-06-11 14:11:00,2018-06-14 17:56:26,2018-06-28,cd76a00d8e3ca5e6ab9ed9ecb6667ac4,botucatu,...,55.790001,47.0,511.0,3.0,30.0,1.0,19.0,600.0,1.0,1.0

In [4]:
ml_table.to_parquet('../data/artifacts/01_ml_table.parquet')

In [5]:
pd.read_parquet('../data/artifacts/01_ml_table.parquet')

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_city,...,total_payment,avg_product_name_length,avg_product_description_length,avg_product_height_cm,avg_product_length_cm,avg_product_photos_qty,avg_product_width_cm,avg_product_weight_g,product_count,seller_count
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,871766c5855e863f6eccc05f988b23cb,campos dos goytacazes,...,72.190002,58.0,598.0,9.0,28.0,4.0,14.0,650.0,1.0,1.0
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,eb28e67c4c0b83846050ddfb8a35d051,santa fe do sul,...,259.829987,56.0,239.0,30.0,50.0,2.0,40.0,30000.0,1.0,1.0
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,3818d81c6709e39d06b2738a8d3a2474,para de minas,...,216.869995,59.0,695.0,13.0,33.0,2.0,33.0,3050.0,1.0,1.0
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,af861d436cfc08b2c2ddefd0ba074622,atibaia,...,25.780001,42.0,480.0,10.0,16.0,1.0,15.0,200.0,1.0,1.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,64b576fb70d441e8f1b2d7d446e483c5,varzea paulista,...,218.039993,59.0,409.0,40.0,35.0,1.0,30.0,3750.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,fffc94f6ce00a00581880bf54a75a037,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,2018-04-25 04:11:01,2018-04-25 12:09:00,2018-05-10 22:56:40,2018-05-18,0c9aeda10a71f369396d0c04dce13a64,sao luis,...,343.399994,43.0,1002.0,15.0,89.0,3.0,40.0,10150.0,1.0,1.0
99437,fffcd46ef2263f404302a634eb57f7eb,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,2018-07-17 04:31:48,2018-07-17 08:05:00,2018-07-23 20:31:55,2018-08-01,0da9fe112eae0c74d3ba1fe16de0988b,curitiba,...,386.529999,31.0,232.0,26.0,45.0,1.0,38.0,8950.0,1.0,1.0
99438,fffce4705a9662cd70adb13d4a31832d,29309aa813182aaddc9b259e31b870e6,delivered,2017-10-23 17:07:56,2017-10-24 17:14:25,2017-10-26 15:13:14,2017-10-28 12:22:22,2017-11-10,cd79b407828f02fdbba457111c38e4c4,sao paulo,...,116.849998,43.0,869.0,24.0,21.0,1.0,19.0,967.0,1.0,1.0
99439,fffe18544ffabc95dfada21779c9644f,b5e6afd5a41800fdf401e0272ca74655,delivered,2017-08-14 23:02:59,2017-08-15 00:04:32,2017-08-15 19:02:53,2017-08-16 21:59:40,2017-08-25,eb803377c9315b564bdedad672039306,vinhedo,...,64.709999,56.0,1306.0,20.0,20.0,1.0,20.0,100.0,1.0,1.0
99440,fffe41c64501cc87c801fd61db3f6244,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,2018-06-09 17:10:13,2018-06-11 14:11:00,2018-06-14 17:56:26,2018-06-28,cd76a00d8e3ca5e6ab9ed9ecb6667ac4,botucatu,...,55.790001,47.0,511.0,3.0,30.0,1.0,19.0,600.0,1.0,1.0